spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframwork.web.client: trace
    org.hibernate.type: trace
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace