spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    sql-script-encoding: UTF-8    
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframwork.web.client: info
    org.hibernate.type: trace