spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframwork.web.client: error
    org.hibernate.type: trace