spring:
  profiles:
    active: test
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
    org.hibernate.type: trace