insert into MEMBER (name, city, street, zipcode)  values('윤민우', '대구', '교학로 2길', '3830-20')
insert into MEMBER (name, city, street, zipcode)  values('정예라', '대구', '서구 2길', '2323-20')
insert into MEMBER (name, city, street, zipcode)  values('김현우', '서울', '목동중앙본로 2길', '111-20')
insert into MEMBER (name, city, street, zipcode)  values('이강남', '서울', '강남대로 44길', '123-20')
insert into MEMBER (name, city, street, zipcode)  values('우하루', '대전', '한밭대 앞 2길', '3830-33')
insert into MEMBER (name, city, street, zipcode)  values('한승연', '오사카', '오사카성 뒤 2길', '333-20')